waldreg/waldreg-api

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java

feat : user 도메인 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java

test : authentication 인수 테스트 추가

---

.gitignore
waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java

feat : user 생성 성공 인수테스트 작성

---

.gitignore
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java

test : 특정 역할 수정 인수테스트 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java

선택가능한 permission 목록 조회 성공, 실패 인수 테스트를 추가함.

test : permission 목록 조회 인수 테스트 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTestHelper.java

refactor : 역할 인수테스트 리팩토링

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java

test : 유저 수정 인수 테스트

---

waldreg/.idea/gradle.xml
waldreg/settings.gradle
waldreg/stable-service-layer/character/build.gradle
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/core/PermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/PermissionVerifiable.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/core/PermissionUnitTest.java

PermissionUnit 객체와 테스트를 추가함.
역할은 PermissionUnit단위로 관리되며, 각 서비스에서 자유롭게 추가가능

feat : 역할 관리 단위 객체 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java

test : 유저 강퇴 인수 테스트

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/DuplicatedPermissionNameException.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownPermissionException.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionUnitManager.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/PermissionUnitManagerTest.java

PermissionUnit을 관리하는 객체와 테스트케이스를 추가함.

feat : PermissionUnit 관리 객체 추가

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/core/PermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionUnitManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/PermissionVerifiable.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/core/PermissionUnitTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/PermissionUnitManagerTest.java

역할 추가 서비스에 Generic을 삭제함.
String으로 선택가능한 status결정하도록 변경

refactor : 역할 추가 서비스 generic삭제

---

waldreg/stable-service-layer/character/build.gradle
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/extension/PermissionExtension.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionUnitManager.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/extension/PermissionExtensionTest.java

새로운 역할과 규칙을 확장하는 역할의 객체를 추가했습니다.

feat : 새로운 역할 확장용 객체 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java

test : delete 추가

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/verification/PermissionVerifier.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/verification/PermissionVerifierTest.java

feat : 권한 인증 객체 추가

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/config/PermissionConfiguration.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/CharacterDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/PermissionDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownPermissionStatusException.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionChecker.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/DefaultPermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/PermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/extension/DefaultPermissionExtension.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/extension/PermissionUnitAddable.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/management/PermissionUnitListReadable.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/management/PermissionUnitManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/verification/DefaultPermissionVerifier.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/verification/PermissionUnitInquiryable.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/verification/PermissionUnitReadable.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/verification/PermissionVerifier.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/DefaultCharacterManagerTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/core/PermissionUnitTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/extension/PermissionExtensionTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/management/PermissionUnitManagerTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/verification/PermissionVerifierTest.java

권한 조회 인터페이스 이름을 보다 직관적으로 변경함.
inquiryable - > readable

refactor : 권한 조회 인터페이스 이름 변경

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/config/PermissionConfiguration.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/CharacterDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/PermissionDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownPermissionStatusException.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionChecker.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/PermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/management/PermissionUnitManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/DefaultCharacterManagerTest.java

새로운 Character 생성 서비스와 테스트들을 추가함.

feat : 새로운 Character 생성 서비스 추가

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java

Character를 수정하는 서비스와 실패, 성공 테스트를 추가함.

feat : Character 수정 서비스 추가

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java

feat : Character 삭제 기능 추가

---

waldreg/.idea/gradle.xml
waldreg/core-layer/util/build.gradle
waldreg/core-layer/util/src/main/java/org/waldreg/util/AnnotationExtractor.java
waldreg/settings.gradle

Util서비스인 AnnotationExtractor을 추가함.

feat : Util서비스 AnnotationExtractor 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java

test : 유저 역할 인수테스트

---

waldreg/core-layer/util/src/main/java/org/waldreg/util/AnnotationExtractor.java
waldreg/core-layer/util/src/main/java/org/waldreg/util/UserIdContextHolder.java
waldreg/core-layer/util/src/test/java/org/waldreg/util/UserIdContextHolderTest.java

토큰을 복호화한 아이디를 교환하는 UserIdContextHolder를 추가함

feat : 토큰 복호화 아이디 교환로직 UserIdContextHolder 추가

---

waldreg/stable-service-layer/character/build.gradle
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/CharacterInUserReadable.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/annotation/PermissionVerifying.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/behavior/VerifyingFailBehavior.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/NoPermissionException.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java

Controller에 PermissionVerifying 어노테이션을 이용해서 권한을 확인하는 기능을 추가함.

feat : Permission 어노테이션 검증 기능 추가

---

waldreg/.idea/gradle.xml
waldreg/repository-layer/memory-repository/build.gradle
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/CharacterMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
waldreg/settings.gradle
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/DuplicatedCharacterException.java

새로운 Character를 Storage에 저장하는 기능과 Chracter 중복체크하는 기능을 추가함.

feat : Character를 저장소에 저장 기능 추가

---

waldreg/service-layer/auth/build.gradle
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java

DecryptedTokenContextHolder에 인증 정보 추가

feat : jwt 인증시 정보 저장 추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/CharacterMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownCharacterException.java

저장된 Character를 조회하는 동작과 테스트 케이스를 추가함.

feat : 저장된 Character 조회 동작 추가

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java

유저id가 갖고있는 역할을 조회하는 기능을 추가했습니다.

feat : 유저id가 갖고있는 역할을 조회하는 기능을 추가함

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java

Character를 수정하는 동작과 실패, 성공테스트를 추가함

feat : Character 수정 동작 추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java

Character를 삭제하는 동작과 실패, 성공 테스트를 추가함

feat : Character 삭제 동작 추가

---

waldreg/.idea/gradle.xml
waldreg/core-layer/util/src/main/java/org/waldreg/util/annotation/AnnotationExtractor.java
waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContext.java
waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContextGetter.java
waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContextHolder.java
waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContextResolver.java
waldreg/core-layer/util/src/test/java/org/waldreg/util/DecryptedTokenContextTest.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java

- DecryptedContext의 인터페이스를 분리함.
- util패키지 역할별로 패키지 분리함.

refactor : util 패키지 리팩토링

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/dto/UserDto.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/UserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java

feat : 유저 보안 조회 서비스

---

waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/UserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java

code for reading specficie user in service layor

feat : read specific user service

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTestHelper.java

- PermissionAcceptanceTestHelper에서 파라미터로 url을 받는것을 지역변수로 수정했습니다.
- 중복 되는 url 호출을 제거하기 위함.

refactor : PermissionAcceptanceTestHelper url 파라미터 리팩토링

---

waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidRangeException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java

feat : 유저 전체 조회 서비스

---

waldreg/.idea/gradle.xml
waldreg/application-layer/application-configurer/build.gradle
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/AdminCharacterConfigurer.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/AdminCharacterCreatedEvent.java
waldreg/application-layer/application-configurer/src/test/java/org/waldreg/ConfigurerTestInitializer.java
waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/character/AdminCharacterConfigurerTest.java
waldreg/settings.gradle

- Application 시작시 "Admin" 역할이 비어있다면, 모든 권한에 대해 성공하는 "Admin" 역할을 기본으로 추가하도록 설정함.

feat : Application 시작시 "Admin" 역할이 없다면 추가하도록 설정

---

waldreg/application-layer/application-configurer/build.gradle
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/GuestCharacterConfigurer.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/GuestCharacterCreatedEvent.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/DecryptedContextResolveInterceptor.java
waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/character/DefaultCharacterConfigurerTest.java

- 애플리케이션 시작시 Guest역할을 기본 역할로 등록했습니다.
- Guest역할은 모든 권한에 대해서 접근 불가능한 역할 이며, 최초 회원가입시 모든 유저는 Guest역할로 지정됩니다.

feat : Guest역할을 기본 역할로 등록

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/aop/PermissionVerifierClient.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/aop/PermissionVerifyAopTest.java

Admin, Guest 권한 삭제시 요청시 No permission 에러를 던지게 수정

fix : Admin, Guest 권한 삭제시 에러던지게 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
waldreg/service-layer/user/build.gradle
waldreg/service-layer/user/src/main/java/org/waldreg/user/dto/UserDto.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserNameException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/UserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java

update user, update user character, delete user own, delete other user service

feat: user update, delete service

---

waldreg/repository-layer/memory-repository/build.gradle
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidIdException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java

feat : Invalid id 예외 추가

---

waldreg/.idea/gradle.xml
waldreg/application-layer/auth-controller/build.gradle
waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/auth/MemoryAuthRepository.java
waldreg/service-layer/auth/build.gradle
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/TokenUserFindById.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/Authenticating.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/HeaderPasswordAuthenticating.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/UserIdAuthenticating.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/behavior/AuthFailBehavior.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/dto/TokenUserDto.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/UserIdMissMatchException.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/AuthRepository.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/TokenUserFindUserIdAndPassword.java
waldreg/service-layer/auth/src/test/java/org/waldreg/token/aop/AuthenticateAopClient.java
waldreg/service-layer/auth/src/test/java/org/waldreg/token/aop/AuthenticateAopTest.java
waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java

- Token 인증 AOP를 추가함.
- Authenticating : 인증만 진행
- HeaderPasswordAuthenticating : HTTP Password header의 값과 토큰 복호화값 비교 진행
- UserIdAuthenticating : UserId와 토큰 복호화값 비교 진행

feat : Token인증 AOP 추가

---

waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/ContextConfigurer.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/DecryptedContextResolveInterceptor.java

application 시작시 DecryptedContextResolverInterceptor 를 기본 인터셉터로 등록함.

feat : DecryptedContextResolverInterceptor 기본 등록 기능 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java

AuthenticationAcceptanceTestHelper 추가

test : Authentication 인수테스트 helper 추가

---

waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/ExceptionTemplate.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/RequestValidationAdvice.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/ExceptionTemplate.java

CharacterController에서 발생한 예외를 잡아서 던지는 기능을 추가함.

feat : CharacterController예외를 잡는 기능을 추가함

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/UserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java

feat : 유저 전체 조회 레포지토리

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/AuthRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java

feat : 유저 삭제 레포지토리

---

waldreg/application-layer/application-configurer/build.gradle
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/ContextConfigurer.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/user/AdminUserConfigurerTest.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/AuthRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java

- 애플리케이션 첫 실행시 Admin 권한을 가진 유저를 기본으로 등록하도록 설정했습니다.

feat : 애플리케이션 첫 실행시 Admin 유저를 기본 유저로 등록하도록 설정

---

waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java

feat : 유저 서비스 관련 권한 등록

---

waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java

- AuthenticateAop에 Order가 적용되지 않아서 PerimssionVerifying보다 먼저 실행되는 버그 수정

fix : AuthenticateAop에 Order가 적용

---

waldreg/application-layer/character-controller/build.gradle
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java

ChracterController에 인증 서비스를 연동했습니다.

feat : CharacterController에 인증 서비스 연동

---

waldreg/application-layer/acceptance/build.gradle

- acceptance모듈에 application-cofigurer의존성을 추가함.

feat : acceptance 모듈application-cofigurer 의존성 추가

---

waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/user-controller/build.gradle
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/ExceptionTemplate.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/UserControllerAdvice.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/mapper/ControllerUserMapper.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UserRequest.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserListResponse.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserResponse.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
waldreg/settings.gradle

User controller, Response, Request code

feat : User Controller code

---

waldreg/.idea/gradle.xml
waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/DecryptedContextResolveInterceptor.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/version/ApiVersionConfigurer.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/version/ApiVersionSetInterceptor.java
waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/request/AuthTokenRequest.java
waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/response/AuthTokenResponse.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/mapper/ControllerUserMapper.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/config/PermissionConfiguration.java

토큰 타입과 토큰을 함께 전달하면 AuthenticateFail 예외가 던저지는 오류를 수정했습니다.

fix : 토큰 타입과 토큰을 함께 전달하면 AuthenticateFail 에러가 나는 오류 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java

- Character Controller에 permission이름을 Character Manager -> Charater manager로 수정함.

fix : Character Controller에 잘못된 Permission 이름이 들어간거 수정

---

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java

- DecryptedToken이 없으면 에러가 던져지는것이 아닌 PASS되도록 수정

fix : DecryptedToken이 없는데 읽을려고 할때 발생하는 오류 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/UserControllerAdvice.java

user 생성 실패 message 설정 오류 수정
토큰 있을 때 특정 유저 조회 시 토큰을 admin 토큰으로 설정

fix : user 생성 성공 인수 테스트 통과, user 특정 유저 조회 성공 인수 테스트 통과

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/UserControllerAdvice.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/AuthenticateFailException.java

없는 유저에 대한 토큰 발급요청 추가, 토큰 발급 실패 테스트 수정

test : 없는 유저에 대한 토큰 발급요청 추가, 토큰 발급 실패 테스트 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java

- PermissionAcceptanceTest를 모두 통과하도록 만듬

test : PermissionAcceptanceTest 모두 성공하게 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/exceptionadvice/AuthExceptionAdvice.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/UserControllerAdvice.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/mapper/ControllerUserMapper.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/CharacterRequest.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UpdateUserRequest.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserListResponse.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java

test : user 인수 테스트 코드 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java

- ADMIN, GUEST 역할을 수정, 삭제 할수 없는지 체크하는 인수테스트를
- 작성하고 테스트함.

test : ADMIN, GUEST 역할 수정, 삭제 불가 인수테스트

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java

[acceptance #1]
-  새로운 유저 생성시 임의의 character(ex. Admin)를 강제로 넘겨주면 어떻게 되는지? -> Guest가 세팅되어야함.
- 여러명의 유저가 Hello라는 character를 갖고있을때 Hello character-name을 Bye로 바꾸면, Hello character를 갖고있던 유저의 character가 Bye로 바뀌는지? -> 바뀌어야함
- Admin비밀번호를 초깃값 0000에서 다른 비밀번호로 변경 가능한지 -> 변경 되어야함.

test : user 인수 테스트 추가

---

waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/cors/CorsWebConfigurer.java

fix : CORS 수정

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/Schedule.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/ScheduleRepeat.java

- Schedule, ScheduleRepeat 도메인을 추가했습니다.

feat : Schedule, ScheduleRepeat 도메인을 추가함.

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Advantage.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Penalty.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Point.java

feat : Schedule 도메인 추가

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/ReactionType.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/category/Category.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/tier/MemberTier.java

- Board, Category, MemberTier domain을 추가 했습니다.

feat : Board, Category, MemberTier domain을 추가함

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java

test : 새로운 일정 생성 인수 테스트

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java

test : 상,벌점 서비스 인수테스트 작성

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java

- code for Inquery Specific Schedule Acceptance Success/Fail Test

test : Inquiry Specific Schedule Acceptance Test

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java

test : 일정 조회 인수 테스트

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java

- code for modify schedule success/fail acceptance test

test : Modify Schedule Acceptance Test

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java

test : 일정 삭제 인수 테스트

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java

- Schedule 인수테스트에 before each/after each로 Initiate 추가함

test : Schedule 인수 테스트 Initiate 추가

---

waldreg/.idea/gradle.xml
waldreg/service-layer/reward/build.gradle
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/RewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/dto/RewardTagDto.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/spi/RewardTagRepository.java
waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
waldreg/settings.gradle

- RewardTag를 생성하는 테스트와 서비스를 추가함.

test : RewardTag 생성 성공 테스트 추가

---

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/RewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/spi/RewardTagRepository.java
waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java

test : rewardtag 업데이트 테스트 추가

---

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/RewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/spi/RewardTagRepository.java
waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java

- reward tag 목록을 조회하는 테스트를 추가함.

test : reward tag 목록 조회를 성공하는 테스트 추가

---

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/lib/TagExceedClipper.java
waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/lib/TagExceedClipperTest.java

- tag 제목이 100자를 넘어간경우 자르는 클래스를 추가함.

feat : tag제목이 100자를 넘어가는경우 자르는 lib클래스 추가

---

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/DefaultUsersRewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/UsersRewardTagManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/spi/UsersRewardTagManagerRepository.java
waldreg/service-layer/reward/src/test/java/org/waldreg/reward/users/UsersRewardTagManagerTest.java

- 특정 유저에게 상점 부여를 성공하는 테스트를 작성했습니다.

test : 특정 유저에게 상점 부여를 성공하는 테스트를 작성함

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java
waldreg/service-layer/schedule/build.gradle
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/dto/RepeatDto.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/dto/ScheduleDto.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/ContentOverflowException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidRepeatException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/StartedAtIsAfterFinishAtException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
waldreg/settings.gradle

- success/fail Test for creating new Schedule Service
- Manager, spi, and Exceptions for creating new Schedule

feat : create new Schedule Service

---

waldreg/repository-layer/memory-repository/build.gradle
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/RewardTagStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/RewardTagMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java

- RewardTag를 저장하는 storage를 추가함.
- RewardTag를 저장하는 로직과 테스트코드를 추가함.

feat : RewardTag 저장소 추가 및 생성 서비스 추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/RewardTagStorage.java

- RewardTagStorage에 RewardTag를 저장하는 메소드를 추가했습니다.

feat : RewardTag를 저장하는 메소드 추가

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidSchedulePeriodException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/StartedAtIsAfterFinishAtException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

feat : 일정 조회 서비스

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/RewardTagStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/RewardTagMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java

- RewardTagStorage에 Read, Update, Delete 기능을 추가했습니다.

feat : RewardTagStorage에 RUD를 추가함

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryRewardTagStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java

- 상벌점이 존재하는지 확인하는 로직과 테스트 코드를 추가했습니다.

feat : 상벌점 존재 확인 로직 추가

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

feat : 일정 수정 서비스

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryRewardTagStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java

feat : 상벌점 업데이트 로직을 추가함

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java

feat : RewardTag 삭제 로직 추가

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

feat : 일정 삭제 서비스

---

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/DefaultUsersRewardManager.java
waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/spi/repository/UsersRewardRepository.java
waldreg/service-layer/reward/src/test/java/org/waldreg/reward/users/UsersRewardManagerTest.java

- UsersRewardManagerRepository -> UsersRewardRepository로 이름을 변경함.

refactor : UsersRewardRepository이름을 변경함

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/UnknownScheduleException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/repository/ScheduleRepository.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

존재하지 않는 일정 id로 조회 시 일정 조회 실패 테스트 작성함

test : 일정 조회 서비스

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

fix : 일정 서비스 테스트

---

waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

- 잘못된 형식의 year, month로 일정 조회시 실패 테스트 작성함

test : 일정 조회 실패 테스트

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/UsersRewardMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java

- 유저가 받은 상점 목록 조회 로직과 테스트를 추가했습니다.

feat : 유저의 상점 목록 조회 로직 추가

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

- Invalid Date format due to DateTimeParseException and fail test
- Invalid Date format due to Under year limit and fail test

test : Update Schedule Service fail test

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java

- 특정 유저에게 부여된 상점을 삭제하는 로직과 테스트코드를 추가했습니다.

feat : 특정 유저에게 부여된 상점 삭제 로직 추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java

- 모든 유저가 받은 상점을 초기화하는 로직을 추가했습니다.

feat : 모든 유저가 받은 상점 초기화 로직 추가

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

- 일정 종료 일자가 시작 일자보다 앞설 경우 실패 테스트 작성

test : 일정 수정 실패 테스트

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java

feat : 유저가 존재하는지 확인하는 로직추가

---

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/config/RewardPermissionConfigurer.java

- Reward manager 권한을 추가함.
- true 로 설정되었다면 Reward와 관련된 모든 권한에 접근 가능
- false 라면 불가능

feat : Reward manager 권한을 추가함

---

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

- 없는 id로 일정 삭제 시도하면 실패하는 테스트 작성함

test : 일정 삭제 실패 테스트 작성

---

waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/RewardController.java

- Reward tag를 삭제하는 컨트롤러를 추가했습니다.

feat : Reward tag 삭제 컨트롤러 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/RewardController.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/mapper/ControllerRewardTagMapper.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/request/RewardTagRequest.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/response/RewardTagResponse.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java

- Reward controller와 Users Reward controller의 위치를 분리했습니다.

refactor : Reward controller 와 Users Reward controller를 분리함

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/Schedule.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/ScheduleRepeat.java
waldreg/repository-layer/memory-repository/build.gradle
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java

feat : 일정 생성 성공 레포지토리

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/cors/CorsWebConfigurer.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/exceptionadvice/RewardControllerAdvice.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/response/RewardTagResponse.java
waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java

- Reward 인수테스트의 잘못된 url 수정
- Reward 인수테스트 검증로직중 예외검증이 잘못된 부분 수정

refactor : Reward 인수테스트 수정

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java

반복이 없을 때 일정 생성이 성공하는 레포지토리 테스트를 작성함

test : 일정 생성 레포지토리 테스트

---

waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/IdAuthenticating.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/parameter/AuthenticateVerifyState.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/IdMissMatchException.java

- User의 id를 기반으로 인증을 진행하는 AOP를 추가함.
- 인증 결과를 파라미터로 전달받을수있도록 수정함.

feat : Id기반 인증 AOP추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java

- code for read Schedule By Term Repository Success Test

test : read Schedule By Term Repository Test

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java

- 특정 일정 조회 성공 레포지토리 테스트를 작성함
- before each, after each로 deleteAll 추가함

test : 특정 일정 조회 레포지토리 성공 테스트

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java

test : 일정 수정 성공 레포지토리 테스트

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java

test : 일정 삭제 레포지토리 성공 테스트

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java

- code for reading specific Schedule Controller

feat : read Specific Schedule Controller

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java

feat : 특정 일정 조회 Controller

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java

feat : 일정 삭제 Controller

---

waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/AdminCharacterConfigurer.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/GuestCharacterConfigurer.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/mapper/ControllerCharacterMapper.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/mapper/ControllerPermissionMapper.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/PermissionRequest.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/CharacterResponse.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/PermissionResponse.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/SimpleCharacterResponse.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/SpecifyStatusPermissionResponse.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/character/Character.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/character/Permission.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/CharacterMapper.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/CharacterDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/PermissionDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownPermissionStatusException.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionChecker.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/DefaultPermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/PermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/management/PermissionUnitManager.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java

- character 에 id 필드를 추가하고 인수테스트를 추가했습니다.
- permission 에 id 필드를 추가하고 인수테스트를 추가했습니다.

feat : character, permission 서비스에 id 필드 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
waldreg/service-layer/schedule/build.gradle
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java

- 토큰 인증 어노테이션 추가
- 새로운 일정 생성 권한 추가

feat : 인증 및 새로운 일정 생성 권한 추가

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java

- Controller에 토큰 인증과 일정 수정 권한을 추가함

feat : 인증 및 일정 수정 권한 추가

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java

- Controller에 일정 삭제 시 토큰 인증과 삭제 권한 추가함

feat : 일정 삭제 권한 및 인증 추가

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ExceptionTemplate.java
waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java

- Controller에 일정 조회 시 토큰 인증 추가함

feat : 일정 조회 인증 추가

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java

- InvalidDateFormatException Handler 추가

feat : InvalidDateFormatException Handler

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java

- InvalidRepeatException Handler 추가함

feat : InvalidRepeatException Handler 추가

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java

InvalidSchedulePeriodException Handler 추가함

feat : InvalidSchedulePeriodExcpetion Handler

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java

- UnknownScheduleException Handler 추가함

feat : UnknownScheduleException Handler 추가

---

waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/request/BoardCreateRequest.java
waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/request/CategoryRequest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/BoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/BlankTitleException.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/ReactionDto.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java

test : board 생성 기능 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/CharacterRequest.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/PermissionRequest.java

- Character 서비스에 예외코드를 추가했습니다.

fix : Character 서비스 예외코드 추가

---

waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/file/exception/DuplicateFileId.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/file/exception/UnknownFileId.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java

feat : 파일 이름 변경 서비스 추가

---

waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java

- 파일 조회 테스트와 서비스를 추가함.
- 파일을 File형태로 조회하는 서비스와 테스트를 추가함.
- 파일을 byte[]형태로 조회하는 서비스와 테스트를 추가함.

feat : 파일 조회 서비스 추가

---

waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/ContentOverflowException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidRepeatException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidSchedulePeriodException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/UnknownScheduleException.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/DuplicatedUserIdException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidRangeException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java

- Schedule Error Exception Template 수정함
- User Error Excpetion Class to final class

fix : Schedule Error Excpetion Template 수정

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java

- 새로운 보드 생성 성공 레포지토리 테스트에서 assertDoesNotThrow에서 assertAll로 변경함

fix : 새로운 보드 생성 성공 레포지토리 테스트

---

waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java

- image와 file이 다른경우 제대로 못잡는 경우를 수정함.

fix : image와 file을 구분하도록 수정함

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCategoryStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/CommentMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/spi/CommentInBoardRepository.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java

- BoardMapper에 있는 commentMapper 리팩토링 : CommentInBoardMapper 인터페이스 분리
- Board Domain에 addComment 메서드 추가
- 댓글 생성 시 해당 보드의 Comment List에 추가하는 메서드 구현

test : 댓글 생성 성공 레포지토리 테스트 작성

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/CommentMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java

- 댓글 수정, 조회, 삭제 테스트 작성
- CommentMapper Refactoring
- 댓글 삭제, 수정 시 Board Domain의 List<Comment>에 반영되도록 로직 추가
(MemoryCommentRepository, MomeroyCommentStorage)

test : Comment Repository Test

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/category/Category.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/CommentMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardInCategoryRepository.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/CategoryRepository.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java

추가 테스트
- Comment storage 에 있던 boardStorage를 Repository로 끌어올림
- Board 삭제, 수정 시 Category Storage에도 반영되도록 BoardRepository에서 처리함

test : Board 삭제, 수정 시 Category Domain 의 BoardList에 반영되도록

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java

레포지토리 테스트
- Board 삭제 시 Board의 CommentList의 Comment들도 삭제되는 로직 추가

test : board 삭제 시 board의 CommentList에 있던 댓글 모두 삭제 성공

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/UserInBoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/MemoryBoardUserInfoRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/UserInfoMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/boarduserinfo/BoardUserInfoRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardUserRepository.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/reaction/management/DefaultReactionManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/reaction/spi/ReactionUserRepository.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/category/CategoryManagerTest.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/reaction/ReactionManagerTest.java

- userDomainToUserDto Refactoring

test : id로 유저 조회 성공 레포지토리 테스트

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/ReactionInBoardRepositoryTest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/ReactionDto.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/reaction/ReactionManagerTest.java

- ReactionInBoardRepository에 storeReactionDto 구현
- board에 해당하는 reaction 값 갱신 성공 레포지토리 테스트 작성함

test : board에 reaction 추가 성공 레포지토리 테스트

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserJoiningPoolListResponse.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserJoiningPoolResponse.java

* 유저 가입 대기열 조회 테스트
* 유저 가입 승인 테스트
* 유저 가입 거절 테스트

test : 유저 가입 대기열 인수테스트 추가

---

waldreg/service-layer/attendance/build.gradle
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/DoesNotRegisteredAttendanceException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/InvalidWaiverDateException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/TooFarDateException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/rule/AttendanceRule.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/rule/valid/AttendanceDateValidator.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/WaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/dto/WaiverDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/waiver/WaiverTest.java
waldreg/settings.gradle

- 출석 면제 요청 테스트를 추가.
- 출석 면제 요청중 발생하는 예외 테스트와 클래스 추가.
- 출석 면제 요청 dto 추가.

test : 새로운 출석 면제 요청 테스트 추가

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/WaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/dto/WaiverDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/waiver/WaiverTest.java

- 출석 면제 요청 읽기 테스트를 추가함.
- 출석 면제 요청을 읽는 코드를 추가함.

feat : 출석 면제 요청 리스트 조회 테스트및 코드 추가

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownAttendanceTypeException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownUsersIdException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownWaiverIdException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceTargetDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/UserExistChecker.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/type/AttendanceType.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/WaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/dto/WaiverDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/waiver/WaiverTest.java

- 출석 면제 승인 서비스를 추가함.
- 출석 면제 승인 테스트를 추가함.

feat : 출석 면제 승인 서비스 추가

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/TooEarlyDateException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceStatusChangeDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceTargetDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/rule/valid/AttendanceDateValidator.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java

- 출석 상태를 강제로 변경하는 서비스를 추가했습니다.
- 관련 테스트케이스를 추가했습니다.

feat : 출석 상태를 강제로 변경하는 서비스 추가

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/InvalidDateException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceDayDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java

- 출석 대상 유저들의 출석 현황을 조회하는 테스트를 추가했습니다.
- 관련 테스트를 추가했습니다.

feat : 출석 대상 유저들의 출석 현황을 조회하는 테스트를 추가함

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceUserDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java

- 자신의 출석 조회 서비스를 추가 했습니다.
- 관련 테스트 케이스를 추가했습니다.

feat : 자신의 출석 조회 서비스를 추가했습니다 

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/AlreadyAttendanceException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/DoesNotStartedAttendanceException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/WrongAttendanceIdentifyException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/valid/AttendanceIdentifyValidable.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java

- 출석 체크 서비스를 추가했습니다.
- 출석 체크 서비스 관련 예외와 테스트케이스를 추가했습니다.

feat : 출석 체크 서비스를 추가함

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryJoiningPoolStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryJoiningPoolRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/ReactionInBoardRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/boarduserinfo/BoardUserInfoRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/JoiningPoolRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/DefaultJoiningPoolManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/JoiningPoolManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/UserManager.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/JoiningPoolRepository.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java

가입 대기열의 repository, storage를 추가함
그에 따른 테스트도 수정

feat : 가입 대기열 repository, storage 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTestHelper.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java

- Acceptance Test For TeamBuilding Service

test : TeamBuilding Acceptance Test

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/AttendanceScheduler.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/dto/AttendanceUserStatusDto.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/spi/AttendanceScheduleRepository.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/spi/AttendanceScheduleRewardRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/event/AttendanceEventTest.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/schedule/AttendanceSchedulerTest.java

- 23:00분 마다 출석 대상 유저에게 상 벌점 부여 서비스를 추가함.
- 관련 테스트 코드를 추가함.

feat : 출석관련 자동 상 벌점 부여 서비스 추가

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/Attendance.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendancePerDate.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceTypeReward.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceUser.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownAttendanceTypeException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownRewardTagIdException.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRewardRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java

- 출석 타입별 상벌점 태그를 연결하는 서비스를 추가했습니다.
- 관련 테스트코드를 추가했습니다.

feat : 출석 타입별 상,벌점 태그 연결 서비스 추가

---

waldreg/repository-layer/memory-repository/build.gradle
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/management/AttendanceManagementRepositoryTest.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/type/AttendanceType.java

- 유저를 출석 대상에 등록하고 조회하는 서비스를 추가했습니다.
- 관련 테스트를 추가했습니다.

feat : 유저를 출석 대상에 등록 및 조회하는 서비스 추가

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/reward/AttendanceRewardManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/reward/DefaultAttendanceRewardManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/reward/spi/AttendanceRewardRepository.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/reward/AttendanceRewardManagerTest.java

- AttendanceManager의 reward tag 관련 메소드를 AttendanceRewardManager로 분리했습니다.
- 관련 테스트 케이스를 추가했습니다.

refactor : AttendanceManager의 reward tag관련 메소드를 분리함

---

waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/AttendanceScheduler.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/spi/AttendanceScheduleRepository.java

- 하루가 지날때마다 새로운 AttendanceCalendar를 생성하는 로직을 추가했습니다.

feat : 하루가 지날때마다 새로운 AttendanceCalendar를 생성하는 로직 추가

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/waiver/Waiver.java

feat : 지각 신청 도메인 추가

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/waiver/Waiver.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/mapper/MemoryWaiverMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepositoryTest.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java

feat : 공결 신청및 조회 서비스 추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepositoryTest.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java

feat : 출석 면제 승인 성공 서비스 추가

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/mapper/MemoryWaiverMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepositoryTest.java

- Waiver을 삭제하는 서비스와 테스트 코드를 추가함.
- Waiver를 단일 조회하는 서비스와 테스트 코드를 추가함.

feat : Waiver 삭제 및 단일 조회 서비스 추가

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

- 특정 teamBuilding 조회 성공 서비스 테스트 및 구현

feat : 특정 teamBuilding 조회 성공 서비스

---

waldreg/service-layer/attendance/build.gradle
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/config/AttendanceConfig.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/config/ScheduleConfig.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/AttendanceScheduler.java

- 출석 관리 역할을 등록함.
- Scheduling 어노테이션을 Config 클래스로 옮김

feat : 출석 관리 역할 등록 

---

waldreg/application-layer/attendance-controller/build.gradle
waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/exceptionadvice/AttendanceControllerAdvice.java
waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/AttendanceController.java
waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/mapper/AttendanceControllerMapper.java
waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/response/AttendanceCheckResponse.java
waldreg/settings.gradle

- 유저를 출석대상에 등록하는 컨트롤러 추가
- 유저를 출석대상에 삭제하는 컨트롤러 추가
- id를 찾을 수 없을때 예외를 잡는 ControllerAdvice 추가

feat : 유저 출석대상 등록,삭제 컨트롤러 추가

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

feat : 전체 팀빌딩 조회 성공 서비스

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

feat : 팀빌딩 수정(팀빌딩 제목 수정) 성공 서비스

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

feat : 팀빌딩 삭제 성공 서비스

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceUserExistChecker.java

- UserExistChecker 가 등록되지 않아 빌드되지 않던 오류 수정

fix : UserExistChecker 등록

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/UnknownTeamBuildingIdException.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

- 특정 팀빌딩 그룹 조회 실패 서비스 테스트 및 구현
- 없는 팀빌딩 id로 조회

feat : 특정 팀빌딩 그룹 조회 서비스 예외 처리

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/InvalidRangeException.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/PerPage.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java

- 팀빌딩 전체 조회 서비스 실패 테스트 및 구현
- 올바르지 않은 범위 설정

feat : 팀빌딩 전체 조회 서비스 예외처리

---

waldreg/application-layer/socket-plugin/build.gradle
waldreg/application-layer/socket-plugin/src/main/java/org/waldreg/socket/config/SocketPluginConfig.java
waldreg/settings.gradle

- socket-plugin 모듈 추가.
- 소켓관련 인터셉터 등의 설정이 이 plugin을 통해 등록될 것임.
- messagebroker 등록
- socket endpoint 추가

feat : socket-plugin 모듈 추가

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

- 팀빌딩 삭제 실패 서비스 테스트 및 구현
- 없는 teambuildingId 삭제 시도

feat : 팀빌딩 삭제 서비스 예외처리

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/UnknownUserIdException.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingUserRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

test : 팀빌딩 그룹 생성 때  존재하지 않는 유저로 생성 시도 시 실패

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTestHelper.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/dto/TeamDto.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/TeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamInTeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java

feat : 팀빌딩 내 팀 수정 성공 서비스

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTestHelper.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/TeamManager.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java

- 팀빌딩 그룹 내 팀이름 변경 성공 서비스 테스트 및 구현

feat : 팀빌딩 그룹 내 팀이름 변경 성공 서비스

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/TeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java

- 팀빌딩 그룹 내 팀 삭제 성공 서비스 테스트 및 구현

feat : 팀빌딩 그룹 내 팀 삭제 성공 서비스

---

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/InvalidUserWeightException.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/UnknownTeamIdException.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java

- update specific team Service fail test and code
- duplicated team name
- user_id already belonging to another team
- unknown team id
- team name overflow
- unknown user id

feat : update specific team Service Exception

---

README.md
waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/mapper/ControllerPermissionMapper.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/PermissionRequest.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/PermissionResponse.java
waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/SpecifyStatusPermissionResponse.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/character/Permission.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/CharacterMapper.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/config/BoardPermissionConfigurer.java
waldreg/service-layer/reward/src/main/java/org/waldreg/reward/config/RewardPermissionConfigurer.java
waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java
waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/config/PermissionConfiguration.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/PermissionDto.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/DefaultPermissionUnit.java
waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/PermissionUnit.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/core/PermissionUnitTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/extension/PermissionExtensionTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/management/PermissionUnitManagerTest.java
waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/verification/PermissionVerifierTest.java

- 유저 서비스 역할 카테고리 추가.
- 보드 서비스 역할 카테고리 추가.
- 상벌점 서비스 역할 카테고리 추가.
- 스케쥴 서비스 역할 카테고리 추가.
- 역할 서비스 역할 카테고리 추가.

feat : 서비스별 역할 카테고리 추가 

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/teambuilding/TeamBuilding.java
waldreg/repository-layer/memory-repository/build.gradle
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamDto.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingsTeamRepository.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

- 팀빌딩 생성 성공 레포지토리 테스트
- 제목으로 팀빌딩 생성 후 팀 목록 생성으로 로직 바뀜에 따라 TeamBuildingManager 로직도 수정

test : 팀빌딩 생성 성공 레포지토리 테스트

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/TeamMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamInTeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java

test : teambuildingId로 team 전체 목록, user 전체 목록 조회 레포지토리

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/TeamMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamInTeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/team/management/DefaultTeamManager.java
waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/teambuilding/management/DefaultTeamBuildingManager.java
waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java

feat : teamBuildingRepo, teamRepo의 변경 사항이 서로 반영 될 수 있게

---

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/TeamMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/UserInTeamMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamInTeamBuildingMapper.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuildinguserinfo/MemoryTeamBuildingUserInfoRepository.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuildinguserinfo/UserInfoMapper.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuildinguserinfo/TeamBuildingUserInfoRepositoryTest.java

- userInfo 가져오기
- user 존재 유무 확인

test : teamBuilding 관련 user Repo 추가

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/user/AdminUserConfigurerTest.java
waldreg/application-layer/user-controller/build.gradle
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/mapper/ControllerUserMapper.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserResponse.java

- User controller build.gradle implementation project 수정
- socialLogin 관련 전부 삭제

fix : User Controller build.gradle

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/Attendance.java
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceTypeReward.java
waldreg/repository-layer/attendance-jpa/build.gradle
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceTypeRewardRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaRewardTagRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/JpaAttendanceTestInitializer.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/TestJpaCharacterRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/TestJpaUserRepository.java
waldreg/repository-layer/attendance-jpa/src/test/resources/h2-application.properties
waldreg/settings.gradle

- JpaAttendanceRepository를 작성함.
- 관련 테스트코드를 작성함.

feat : JpaAttendanceRepository 작성

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTestHelper.java
waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/BoardController.java

fix : board controller 의 카테고리별 전체조회 url을 수정

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/waiver/Waiver.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaUserRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaCharacterRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaUserRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/JpaWaiverRepositoryTest.java
waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java

- JpaWaiverRepository를 작성함.
- 관련 테스트 코드를 작성함.

feat : JpaWaiverRepository 작성

---

waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/valid/AttendanceValidatorRepositoryServiceProvider.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/valid/AttendanceValidatorRepositoryServiceProviderTest.java

- MemoryAttendanceValidator -> JpaAttendanceValidator로 변경.
- 관련 테스트 코드 추가.
- 관련 ServiceProvider 추가.

feat : MemoryAttendanceValidator -> JpaAttendanceValidator

---

waldreg/application-layer/attendance-controller/build.gradle
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/management/AttendanceRepositoryServiceProvider.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/management/UserExistCheckerServiceProvider.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaUserRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/reward/AttendanceRewardRepositoryServiceProvider.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/reward/repository/JpaAttendanceRewardTagRepository.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/WaiverRepositoryServiceProvider.java
waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverUserRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaUserRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/management/AttendanceRepositoryServiceProviderTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/reward/AttendanceRewardRepositoryServiceProviderTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/reward/TestJpaRewardTagRepository.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRepositoryServiceProviderTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRewardRepositoryServiceProviderTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/valid/AttendanceValidatorRepositoryServiceProviderTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/JpaWaiverServiceProviderTest.java
waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverRepositoryTest.java

- MemoryAttendanceRewardRepository -> JpaAttendancerewardRepository로 변경함.
- 관련ServiceProvider 작성.
- 관련 테스트 코드 작성.

feat : MemoryAttendanceRewardRepository -> Jpa...Repository

---

waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
waldreg/repository-layer/auth-jpa/build.gradle
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/AuthRepositoryServiceProvider.java
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/mapper/AuthRepositoryMapper.java
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaBoardRepository.java
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaCategoryRepository.java
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaCharacterRepository.java
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaCommentRepository.java
waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaUserRepository.java
waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/AuthRepositoryTest.java
waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/JpaAuthTestInitializer.java
waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/repository/JpaUserRepositoryTest.java
waldreg/repository-layer/auth-jpa/src/test/resources/h2-application.properties
waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/auth/MemoryAuthRepository.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/authenticator/TokenAuthenticator.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/AuthRepository.java
waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/TokenUserFindUserIdAndPassword.java
waldreg/settings.gradle

refactor : 패스워드 불일치 에러를 서비스 레이어로 이동

feat : auth-jpa 작성 & refactor : 에러 핸들링

---

waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/comment/request/CommentRequest.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/BoardTitleOverFlowException.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/CategoryNameOverFlowException.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/ContentOverFlowException.java

board title 길이제한 250자 추가
comment overflow 변경
comment content 길이제한, notBlank 추가
category name 길이제한 50자 추가

feat : board 관련 예외를 추가함

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java

fix : board views 버그 수정

---

README.md
waldreg/application-layer/acceptance/build.gradle
waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java

[fix : board views 버그 수정](https://github.com/waldreg/waldreg-api/commit/77b81af2cdf580ac11c3c63f3a4b1f7edd23cf05)

0.5.2.1 : Board의 조회수가 증가하지 않는 버그 수정

---

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTestHelper.java
waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/CategoryController.java
waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/mapper/ControllerCategoryMapper.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/CategoryManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
waldreg/service-layer/board/src/test/java/org/waldreg/board/category/CategoryManagerTest.java

feat : 특정 카테고리 조회 인수테스트 작성

---

README.md
waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/joiningpool/request/UserRequest.java
waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UpdateUserRequest.java

Release 0.5.4 

---

README.md
waldreg/application-layer/acceptance/build.gradle
waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CategoryRepositoryServiceProvider.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java

- 카테고리 업데이트시 저장되어있던 게시글이 조회되지 않는 버그 수정.

Release 0.5.5

---

waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/HomeRepositoryServiceProvider.java
waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/repository/HomeJpaRepository.java
waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/HomeRepositoryServiceProviderTest.java
waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/JpaHomeTestInitializer.java
waldreg/repository-layer/home-jpa/src/test/resources/h2-application.properties

- DB에서 홈화면의 게시글을 조회하는 서비스를 생성함.
- 관련 테스트케이스 생성 및 통과

feat : DB에서 홈화면 게시글 조회 서비스 생성

---

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/home/ApplicationColor.java
waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/ColorRepositoryServiceProvider.java
waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/repository/ColorJpaRepository.java
waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/ColorRepositoryServiceProviderTest.java

- DB에서 Color를 수정하고 조회하는 서비스를 추가했습니다.
- 관련 테스트코드를 추가했습니다.

feat : DB에서 Color 수정 및 조회 서비스 추가

---

waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/config/HomeInitializer.java

- 애플리케이션 시작시, 색상, 홈 글 DB에 어떠한 내용도 없다면, 초기 글과 색상을 초기화 하도록 했습니다.
- 색상 : application-color : #2d2d2d / background-color : #2d2d2d
- 글 : Hello world...

fix : 초기 홈화면 글, 색깔 설정 클래스 추가

---

waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/BoardController.java
waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/mapper/ControllerBoardMapper.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java

카테고리, 전체조회 등은 카테고리별 게시글 개수, 전체 개시글 개수가 maxIdx 가 되도록 함. 검색은 검색 결과 개수가 maxIdx가 되도록 함.

fix : maxIdx 를 총 게시물 개수로 수정함.
