waldreg/waldreg-api

waldreg/core-layer/util/src/main/java/org/waldreg/util/DecryptedTokenContextHolder.java, waldreg/core-layer/util/src/test/java/org/waldreg/util/DecryptedTokenContextHolderTest.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java, waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
UserIdContextHolder의 이름을 DecrytedTokenContextHolder로 변경함. UserIdContext의 resolve메소드를 resolve메소드와 get메소드로 분리함.
=> refactor : UserIdTokenContextHolder 리팩토링

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/annotation/PermissionVerifying.java
- @PermissionVerifying 에 Target 과 Retention 을 적용하지 않아서 동작하지 않던 오류 수정
- PermissionVerifyAop 에서 @PermissionVerifying 의 경로를 잘못 설정해서 빈이 로딩되지 않던 오류 수정
=> fix : PermissionVerifying 이 적용되지 않던 오류 수정

waldreg/core-layer/util/src/main/java/org/waldreg/util/DecryptedTokenContextHolder.java, waldreg/core-layer/util/src/main/java/org/waldreg/util/exception/DecryptedTokenDoesNotExistException.java
- Decrypted된 token이 없는데, DecryptedTokenContextHolder에 get()요청을 한 경우, 유의미한 예외를 반환하도록 수정함.
- NullPointerException.class -> DecryptedTokenDoestNotExistException.class
=> fix : Decrypted 된 token이 없을경우 유의미한 예외를 반환하도록 수정함

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/parameter/PermissionVerifyState.java
VerifyingFailBehavior를 fail로 설정하고,
PermissionVerifyState 인터페이스를 파라미터로 등록하면, 권한 확인 성공 유무를 전달합니다.
=> feat : 권한 확인 결과를 파라미터로 값을 전달하는 기능 추가

waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
- CharacterControllerAdvice가 UnknownPermissionException.class 와 UnknownPermissionStatusException.class를 잡고 둘중 한 타입으로 파라미터를 받는 오류를 수정했습니다.
=> fix : CharacterControllerAdvice 잘못된 파라미터 수정

waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/parameter/PermissionVerifyState.java, waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/aop/PermissionVerifyAopTest.java
- PermissionVerifyState를 함수형 인터페이스에서 클래스로 변경함
- 함수형 인터페이스는 기본생성자가 없어서 Controller메소드에서 주입 받을 수 없음
=> fix : PermissionVerifyState를 클래스로 변경함.

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java, waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/RequestValidationAdvice.java, waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/SpecifyStatusPermissionResponse.java, waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
- 기존에 Character생성시 permission이 비어있으면, 해당 permission을 지정해주지 않았는데,
- 이제부터는 permission이 비어있으면 비어있는 permission은 항상 실패하는 permission으로 지정해줌
=> fix : 새로운 Character생성시 permission이 비어있다면, 없는권한으로 지정

Dockerfile, waldreg/Dockerfile
Dockerfile실행전 jar 파일을 빌드 하지 않아도 되도록 변경함.
=> chore : Dockerfile 위치변경

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Advantage.java, waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Penalty.java, waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Point.java, waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java, waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java, waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
- user 도메인의 상, 벌점을 원시타입에서 객체로 바꿨습니다.
- userMapper 의 domainToDto로직과 updateUser로직을 상, 벌점을 초기화 하지않도록 변경 했습니다.
=> refactor : user 도메인의 상, 벌점을 원시타입에서 객체로 바꿈

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/lib/TagExceedClipper.java, waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/lib/TagExceedClipperTest.java
- tag 점수가 -1000~1000 사이가 아니라면, 강제로 조정하는 서비스를 추가했습니다.
=> test : tag 점수가 -1000, 1000 사이가 아닐경우 강제로 조정하는 서비스 추가

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java, waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/lib/TagExceedClipper.java, waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
- reward tag의 제목과 점수가 각각 100, (-1000~1000)을 초과하지 않도록 변경했습니다.
=> fix : reward tag의 제목과 점수가 각각 100, -1000~1000 을 초과하지 않도록 변경함

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java, waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/exception/UnknownRewardTagException.java, waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
- reward tag 업데이트시 tag를 찾을 수 없으면
- UnknownRewardTagException.class 예외를 반환하도록 수정했습니다.
=> fix : reward tag 업데이트시 tag를 찾을 수 없으면 예외를 반환하도록 수정

waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/DefaultUsersRewardManager.java, waldreg/service-layer/reward/src/test/java/org/waldreg/reward/users/UsersRewardManagerTest.java
- 특정 유저의 상,벌점 조회시 유저를 찾을 수 없는 예외 상황을 고침
=> fix : 특정 유저의 상,벌점 조회시 유저를 찾을 수 없는 예외 상황 수정

waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/rewardtag/RewardTag.java
- RewardTag도메인의 Builder가 private 접근제어자로 되어있는걸 수정함.
- RewardTag도메인의 rewardTagId를 Builder가 아닌 setter로 제어하도록 수정함.
=> fix : RewardTag 도메인의 오타 수정및 id setter 추가

waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java, waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java, waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
- 변수명 대문자 오류(StartedAt) 수정
- repeatDto 관련 예외 테스트 작성
- 잘못된 cycle 값을 입력한 경우
- 반복 종료 날짜가 일정 날짜보다 앞서는 경우
- 반복 종료 날짜 형식이 잘못된 경우
=> test : 유저 수정 실패 테스트 작성

waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/MemoryCategoryRepository.java, waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
성공 레포지토리 테스트
- Category 삭제 시 Category domain의 BoardList에 있던 Board들도 함께 삭제되도록 로직 추가함
=> test : Category 삭제 시 Category의 BoardList에 있던 Board도 함께 삭제

waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java, waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/ContentOverflowException.java, waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/InvalidTeamCountException.java, waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/InvalidUserWeightException.java, waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java, waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
- 새로운 팀빌딩 생성 실패 서비스 테스트 및 구현
- 팀빌딩 제목 길이 초과
- 팀 개수 0개 이하 설정
- 유저 가중치 범위 벗어남
- 팀 개수가 유저 수 초과
=> feat : 새로운 팀빌딩 생성 서비스 예외 처리

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java, waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
- 팀빌딩 수정 서비스 실패 테스트 및 구현
- 없는 팀빌딩 id로 수정 시도
- 1000자 이상의 팀빌딩 제목으로 수정 시도
=> feat : 팀빌딩 수정 서비스 예외처리

waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java, waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java
- 팀빌딩 그룹 내 팀이름 변경 서비스 실패 테스트 및 구현
- 없는 team_id
- 중복된 team_name
- team_name 1000자 초과
=> feat : 팀빌딩 그룹 내 팀이름 변경 서비스 예외 처리

waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java, waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/CharacterRequest.java
- character_name 필드가 25자를 넘어가면 예외 메시지를 전달하도록 수정했습니다.
=> fix : character_name의 길이가 25를 넘어가지 않도록 수정
